DELETE http://localhost:8080/events/1/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QtMkBhcGkuY29tIiwiZXhwIjoxNzUyNzczODQ3LCJ1c2VySWQiOjJ9.0o8mNSjp580LmPDRQwZs5jlXIpleY28_PFUcV_8zRo4