POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYXBpLmNvbSIsImV4cCI6MTc1MjczMzExMywidXNlcklkIjoxfQ.oThtA7nTfEBsf136ykwOCqqZnGqEuGdTww9nf8n1RFI

{
    "name":"my test event",
    "description":"my event Party",
    "location":"my location",
    "datetime": "2025-07-07T15:30:00.000Z"
}