POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYXBpLmNvbSIsImV4cCI6MTc1MjY5ODExMywiaWQiOjB9.ApNci8Awe7yUswhZOjrCgw7jzJOluZ6aHXheOqPNO1c

{
    "name":"test event",
    "description":"test event Party",
    "location":"test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}