DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYXBpLmNvbSIsImV4cCI6MTc1MjczNDE4NywidXNlcklkIjoxfQ.Vd49I_NuJJ798pmltVkfnrmR5l03fSFXvxiK-tu6hSg