PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYXBpLmNvbSIsImV4cCI6MTc1MjczMzExMywidXNlcklkIjoxfQ.oThtA7nTfEBsf136ykwOCqqZnGqEuGdTww9nf8n1RFI

{
    "name":"test event 2",
    "description":"test event 2",
    "location":"test location 2",
    "datetime": "2025-07-15T09:01:00Z"
}