PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld3Rlc3RAYXBpLmNvbSIsImV4cCI6MTc1MjczMjIyMywidXNlcklkIjoyfQ.swTqfSpDAIuU1KOzWc53vR9ThuEjxcOedRBBTufUi3Q

{
    "name":"test event 2",
    "description":"test event 2",
    "location":"test location 2",
    "datetime": "2025-07-15T09:01:00Z"
}